Ltak 187 create page for coding dojo
lenneTech/lennelearning pull request #395
Opened 2023-07-10 10:34 UTC by vincnt28

Image Gallery not finished yet

2023-07-10 13:53 UTC, vincnt28 commented
need to have the gallery pushed @DKoenig9

2023-07-12 09:30 UTC, DKoenig9 requested changes

2023-07-12 09:30 UTC, DKoenig9 commented on src/app/modules/core/components/banner/banner.component.scss
> +}
Remove this class when you also removed it in the template.

2023-07-12 09:56 UTC, DKoenig9 requested changes

2023-07-12 09:56 UTC, DKoenig9 commented on src/app/modules/core/components/banner/banner.component.html
> +        <button class="scndBtn mt-3 me-3" nbButton>
Suggestion: set width of both buttons to 50% on mobile and when they are displayed in a row set it to "fit-content"

2023-07-12 09:56 UTC, DKoenig9 commented on src/app/modules/core/components/banner/banner.component.html
> +      <button class="ms-5" nbButton status="primary" *ngIf="showDojoBtn" data-cy="entry-point-btn">
Because of "ms-5" the button gets displayed strange on mobile --> instead set the margin-left when the md-breakpoint is crossed

2023-07-12 09:56 UTC, DKoenig9 commented on src/app/modules/core/components/information-showcase/information-showcase.component.html
> +          <i class="bi bi-8-circle m-n-5 fs-4"></i>
Suggestion:
This classes were added by me but there is a better solution: For a negative margin you can use bootstrap
--> instead of "m-n-5" you can use the class "mt-n2". This classes are disabled by default but can be enabled by writing the following code inside the bootstrap-overwrites.scss:
$enable-negative-margins: true

2023-07-17 05:33 UTC, vincnt28 commented on src/app/modules/core/components/workshop-info/workshop-info.component.ts
> +  };
The string array, get renamed to "schools" and is remaining in the comp.ts, to reduce code

2023-07-17 06:50 UTC, DKoenig9 requested changes

2023-07-17 06:50 UTC, DKoenig9 commented on src/app/modules/core/components/banner/banner.component.scss
> +      display: fit-content;
"fit-content" is an invalid value for property display --> You can use this value in the width-attribute. But you also can leave width set to "auto" because this seems to display the buttons the same way as "fit-content" would do.

2023-07-17 06:50 UTC, DKoenig9 commented on src/app/modules/core/components/header/header.component.html
>              <app-underline-animation currentRoute="{{ getCurrentRoute().endsWith('/dojo') }}">
The underline-animation is not active when the user is on the codingdojo-page. Rename this route to "codingdojo" as well

2023-07-17 10:57 UTC, DKoenig9 approved these changes

2023-07-17 10:57 UTC, merged